CAMERA_INDEX = 1

FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

MIN_OBJECT_AREA = 1000

SHOW_MASK = False

POSITION_HISTORY_LEN = 8
MIN_DIRECTION_HISTORY = 4
MIN_DIRECTION_MOVEMENT_PX = 15

TILE_CAPTURE_INTERVAL_SEC = 2.0

MAX_REACQUIRE_STEP_DEG = 45

SUPPRESSION_RADIUS_PX = 100
SUPPRESSION_ZONE_EXPIRY_SEC = 15
VERIFICATION_CROP_PADDING_RATIO = 0.5

LLAMA_SERVER_PORT = 18080
GPU_DEGENERATE_RETRIES = 3

USE_YOLO_TRACKER = True
YOLO_TARGET = "red cup"

GATE_REJECT_MIN_DEFECTS = 2
GATE_REJECT_MAX_SOLIDITY = 0.75